language: php

matrix:
  include:
    - php: 5.3
      dist: precise
    - php: 5.4
      dist: trusty
    - php: 5.5
      dist: trusty
    - php: 5.6
      dist: xenial
    - php: 7.0
      dist: xenial
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - COMPOSER_MEMORY_LIMIT=-1 composer update --no-interaction

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls --verbose
  - CODECLIMATE_REPO_TOKEN=de49d0a5bf2f0b3194dbbcedd106fec725ab5dce346bd603d3653f9237b3ebba ./vendor/bin/test-reporter
