language: php

matrix:
  include:
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
    - php: 5.4
    - php: 5.3
      dist: precise

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction

script:
  - mkdir -p build/logs
  - phpunit --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
  - CODECLIMATE_REPO_TOKEN=de49d0a5bf2f0b3194dbbcedd106fec725ab5dce346bd603d3653f9237b3ebba ./vendor/bin/test-reporter
